version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - server1
      - server2
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  server1:
    build:
      context: .
    depends_on:
      - db
      - redis
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
      - /app/node_modules

  server2:
    build:
      context: .
    depends_on:
      - db
      - redis
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
      - /app/node_modules

  
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: unless-stopped

volumes:
  postgres_data: