version: '3.8'

services:
  server:
    build:
      context: .
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
    environment:
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data: