name: Backend CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            echo "Deploying to EC2..."

            cd /home/ec2-user/swapit-server || exit 1
            echo "Pulling latest code..."
            git pull || { echo "Git pull failed"; exit 1; }

            echo "Stopping existing containers..."
            docker-compose down || { echo "Failed to stop containers"; exit 1; }

            echo "Building new containers..."
            docker-compose build --no-cache || { echo "Build failed"; exit 1; }

            echo "Starting new containers..."
            docker-compose up -d || { echo "Failed to start containers"; exit 1; }

            echo "Pruning unused images..."
            docker image prune -f

            echo "Deployment completed successfully"
