name: Backend CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    types:
      - completed

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ec2-user/code/swapit-server
            git pull || exit 1
            npm ci
            npm run build

            docker --version
            sudo systemctl status docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER
            ls -l /var/run/docker.sock
            docker-compose --version

            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
            docker image prune -f
